export const CATEGORY_IMAGES: Record<string, string> = {
    Breakfast: "https://images.unsplash.com/photo-1493770348161-369560ae357d?auto=format&fit=crop&q=80&w=800",
    Main: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80&w=800",
    Dessert: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800",
    Side: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=800",
    Appetizer: "https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&q=80&w=800",
    Bread: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800",
    'Dip/Sauce': "https://images.unsplash.com/photo-1541414779316-956a5084c0d4?auto=format&fit=crop&q=80&w=800",
    Snack: "https://images.unsplash.com/photo-1629115916087-7e8c114a24ed?auto=format&fit=crop&q=80&w=800",
    Generic: "https://images.unsplash.com/photo-1495195129352-aec325a55b65?auto=format&fit=crop&q=80&w=800"
};

export const HERITAGE_AVATARS = [
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Felix&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Aria&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Leo&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Milo&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Luna&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Jasper&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Willow&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Jack&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Sasha&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Oliver&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Cleo&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Sam&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Nala&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Ziggy&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Daisy&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Oscar&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Ruby&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Toby&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Zoe&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Finn&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Bella&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Hugo&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Molly&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Arlo&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucy&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Rex&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Penny&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Otis&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Heidi&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Gus&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Gigi&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Barnaby&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Bibi&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Caspian&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Coco&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Dante&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Dora&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Elio&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Evie&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Flynn&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Flora&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Gideon&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Hazel&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Isaac&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Ivy&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Jude&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=June&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Koa&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Kiki&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Linus&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Lola&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Magnus&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Maya&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Nico&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Nina&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Phineas&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Phoebe&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Quincy&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Quinn&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Rocco&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Rosa&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Silas&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Stella&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Theodore&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Tessa&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Ulysses&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Uma&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Viggo&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Vera&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Winston&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Willa&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Xander&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Xanthe&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Yosef&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Yara&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Zia&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Zeke&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Arthur&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Beatrice&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Clarence&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Dorothy&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Ernest&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Florence&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=George&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Harriet&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Irving&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Joyce&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Kenneth&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Lillian&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Milton&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Nellie&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Oswald&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Pearl&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Ralph&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Ruth&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Stanley&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Thelma&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Victor&mouth=smile&eyes=default",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Viola&mouth=smile&eyes=default"
];
