export const CATEGORY_IMAGES: Record<string, string> = {
    Breakfast: "https://images.unsplash.com/photo-1493770348161-369560ae357d?auto=format&fit=crop&q=80&w=800",
    Main: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80&w=800",
    Dessert: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800",
    Side: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=800",
    Appetizer: "https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&q=80&w=800",
    Bread: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800",
    'Dip/Sauce': "https://images.unsplash.com/photo-1541414779316-956a5084c0d4?auto=format&fit=crop&q=80&w=800",
    Snack: "https://images.unsplash.com/photo-1629115916087-7e8c114a24ed?auto=format&fit=crop&q=80&w=800",
    Generic: "https://images.unsplash.com/photo-1495195129352-aec325a55b65?auto=format&fit=crop&q=80&w=800"
};

export const HERITAGE_AVATARS = [
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Felix",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Aria",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Leo",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Milo",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Luna",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Jasper",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Willow",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Jack",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Sasha",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Oliver",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Cleo",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Sam",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Nala",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Ziggy",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Daisy",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Oscar",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Ruby",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Toby",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Zoe",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Finn",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Bella",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Hugo",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Molly",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Arlo",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucy",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Rex",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Penny",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Otis",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Heidi",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Gus",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Gigi",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Barnaby",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Bibi",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Caspian",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Coco",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Dante",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Dora",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Elio",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Evie",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Flynn",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Flora",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Gideon",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Hazel",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Isaac",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Ivy",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Jude",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=June",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Koa",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Kiki",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Linus",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Lola",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Magnus",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Maya",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Nico",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Nina",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Phineas",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Phoebe",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Quincy",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Quinn",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Rocco",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Rosa",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Silas",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Stella",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Theodore",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Tessa",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Ulysses",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Uma",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Viggo",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Vera",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Winston",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Willa",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Xander",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Xanthe",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Yosef",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Yara",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Zia",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Zeke",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Arthur",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Beatrice",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Clarence",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Dorothy",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Ernest",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Florence",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=George",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Harriet",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Irving",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Joyce",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Kenneth",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Lillian",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Milton",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Nellie",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Oswald",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Pearl",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Ralph",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Ruth",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Stanley",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Thelma",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Victor",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Viola"
];
