/** All localStorage keys used by the app */
export const STORAGE_KEYS = {
  user: 'schafer_user',
  firebaseConfig: 'schafer_firebase_config',
  activeProvider: 'schafer_active_provider',
  archivePhone: 'schafer_archive_phone',
  dbRecipes: 'schafer_db_recipes',
  dbGallery: 'schafer_db_gallery',
  dbTrivia: 'schafer_db_trivia',
  dbContributors: 'schafer_db_contributors',
  dbHistory: 'schafer_db_history',
  favorites: 'schafer_favorites',
  recentlyViewed: 'schafer_recently_viewed',
  triviaScores: 'schafer_trivia_scores',
  ratings: 'schafer_ratings',
  notes: 'schafer_notes',
  collections: 'schafer_collections',
  theme: 'schafer_theme',
  fontSize: 'schafer_font_size',
  highContrast: 'schafer_high_contrast',
  onboardingDone: 'schafer_onboarding_done',
  activityFeed: 'schafer_activity_feed',
} as const;
