import type { Recipe } from '../types';

/**
 * A recipe image URL is renderable only when it points at a bundled asset
 * (`/recipe-images/...`) or an absolute http(s) URL. Anything else (empty
 * strings, relative junk, data we can't trust) falls back to a placeholder.
 */
export const isValidRecipeImageUrl = (url: string | undefined | null): url is string =>
    !!url && (url.startsWith('/recipe-images/') || url.startsWith('http://') || url.startsWith('https://'));

/**
 * The responsive width variants generated by
 * `scripts/generate-responsive-images.mjs` for every bundled recipe photo.
 * Keep in sync with the WIDTHS array there.
 */
export const RECIPE_IMAGE_VARIANT_WIDTHS = [480, 800] as const;

/**
 * Build an `<img srcset>` for a bundled recipe photo so the browser can pick a
 * width-appropriate variant (e.g. a 480px card on mobile instead of the full
 * 1200px source). Returns `undefined` for external URLs or anything that isn't
 * a bundled `/recipe-images/<id>.webp` — those have no generated variants.
 *
 * Example: `/recipe-images/abc.webp` →
 *   "/recipe-images/abc-480.webp 480w, /recipe-images/abc-800.webp 800w, /recipe-images/abc.webp 1200w"
 */
export function buildRecipeImageSrcSet(url: string | undefined | null): string | undefined {
    if (!url || !url.startsWith('/recipe-images/') || !url.endsWith('.webp')) return undefined;
    // Never build variants from a variant path (defensive against double-calls).
    if (/-\d+\.webp$/.test(url)) return undefined;
    const base = url.slice(0, -'.webp'.length);
    const parts = RECIPE_IMAGE_VARIANT_WIDTHS.map((w) => `${base}-${w}.webp ${w}w`);
    // The original source is the largest (1200px) candidate.
    parts.push(`${url} 1200w`);
    return parts.join(', ');
}

/**
 * "Cookbook cover" images are locally generated portrait art meant to be shown
 * matted (object-contain) rather than bled to the edges (object-cover).
 */
export const isCookbookCoverImage = (recipe: Pick<Recipe, 'imageSource'>): boolean =>
    recipe.imageSource === 'local-generated';

/**
 * Handwritten recipe-card scans read better as category art in dense grids;
 * the full card photo still shows in the recipe modal.
 */
export const isHandwrittenRecipeCard = (
    recipe: Pick<Recipe, 'imageSource' | 'imageApprovalStatus' | 'generatedImageFallback' | 'notes'>,
): boolean => {
    if (recipe.imageSource !== 'upload' || recipe.imageApprovalStatus !== 'approved') return false;
    if (recipe.generatedImageFallback === true) return false;
    const notes = recipe.notes?.toLowerCase() ?? '';
    return notes.includes('handwritten') || notes.includes('recipe card');
};
